/* jshint quotmark: false */
"use strict";
// DO NOT EDIT THIS FILE, EDIT THE GULP TASK NGCONSTANT SETTINGS INSTEAD WHICH GENERATES THIS FILE
angular.module("bugu")

.constant("ENV", "prod")

.constant("API_ENDPOINT", "http://www.bookbugu.com/")

.constant("VERSION", 1)

;